apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sejokimapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sejoonkimmm/iot-argoCD.git
    targetRevision: HEAD
    path: deploy # deploy 폴더 내에 있는 쿠버네티스 매니페스트 파일을 사용하여 dev namespace에 애플리케이션을 배포할 것이다.
  destination:
    server: 'https://kubernetes.default.svc' # 쿠버네티스 기본 서버를 사용한다
    namespace: dev # dev namespace에 배포할 것이다.