Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", create: true
  config.vm.define "sejokimS" do |server|
    server.vm.box = "generic/alpine319"
    server.vm.hostname = "sejokimS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--name", "sejokimS"]
    end
    server.vm.provision "shell", path: "scripts/deploy.sh"
  end
end
