Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", create: true
  config.vm.define "sejokimS" do |master|
    master.vm.box = "generic/alpine319"
    master.vm.hostname = "sejokimS"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "sejokimS"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "sejokimS"]
      master.vm.network "private_network", ip: "192.168.56.110"
    end
    master.vm.provision "shell", path: "scripts/server.sh"
  end
  # worker config
  config.vm.define "sejokimSW" do |worker|
    worker.vm.box = "generic/alpine319"
    worker.vm.hostname = "sejokimSW"
    worker.vm.provider "virtualbox" do |v|
      v.name = "sejokimSW"
      v.memory = 1024
      v.cpus = 1
      worker.vm.network "private_network", ip: "192.168.56.111"
      v.customize ["modifyvm", :id, "--name", "sejokimSW"]
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end